name: Testing 🧪
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "public" ]
    paths-ignore:
      - 'README.md'  # Exclude changes to the README.md file
      - '.run/**'
      - 'files/**'

jobs:
  build-and-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests on JVM
        run: xvfb-run ./gradlew desktopTest
